name = "familytree-api"
main = "worker.js"
compatibility_date = "2026-08-01"
account_id = "4b65c3e179376d3874d25be52073276d"

routes = [
  { pattern = "jpcoakley.com/api/familytree*", zone_name = "jpcoakley.com" }
]

[[kv_namespaces]]
binding = "FT_KV"
id = "c30d7711f1ba477f92b69793ed158928"
